### PR TITLE
Add common type of time units and `std::chrono::duration`

### PR DESCRIPTION
**Pull request by johelegp**
Working towards correct `std::common_type` specializations. First, put everything in one place.

### CODE REVIEW

**Comment by johelegp** [comment]
> This is ready.

Actually, wait. This change and previous specializations also failed to meet this requirement: ["a program may specialize `common_­type<T1, T2>` for types `T1` and `T2` such that `is_­same_­v<T1, decay_­t<T1>>` and `is_­same_­v<T2, decay_­t<T2>>` are each `true`."](http://eel.is/c++draft/meta#trans.other-5.sentence-1). Partial specializations that use a template parameter as an argument in the _argument-list_ of the specialization, like this [`StrongUnit`](https://github.com/nholthaus/units/pull/217/files#diff-66d5febae528de60895295a0d564fbc3L394) or this [`T`](https://github.com/nholthaus/units/pull/217/files#diff-66d5febae528de60895295a0d564fbc3R374), could accept types that weren't the same if decayed. That would mean that for each strong unit of the same dimension, say `millimeters` through `kilometers`, you'd have to "manually" define partial specializations in pairs of all their combinations. And this has to expand to non-`meters` length units, like `feet`. This is unreasonable, and explodes the amount of symbols in the library even more. `std::common_type` has a really unfriendly interface for specializing in cases such as this.

What do you think about solving this be reverting making the units strong types?

**Comment by johelegp** [comment]
Changed the scope of the PR to adding these `std::common_type` specializations between time units and `std::chrono::duration` specializations.

**Comment by nholthaus** [comment]
@johelegp I'm a bit confused by the comment timeline between this and #219, but I think that we still want to pull this PR even if we revert strong units?

**Comment by johelegp** [comment]
That's right.

**Comment by nholthaus** [comment]
I made an attempt to resolve the conflicts but I wasn't confident in the results. Would you mind taking a stab at it?

**Pull request merged**
