### PR TITLE
Clang format

### LINKED ISSUE #117: clang-format support
Would you like me to build a .clang-format file for formatting the header? I'd choose the options that keep intact as much code as possible. This would be with done with Clang 6 and the HEAD of branch v3.x.

### PR DESCRIPTION
**Pull request by johelegp**
Resolves #117.

### CODE REVIEW

**Comment by johelegp** [comment]
Note that some sections are [disabled for formatting](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#disabling-formatting-on-a-piece-of-code).

**Comment by johelegp** [comment]
Now that we can let the formatting be done automatically, you might want to consider changing the [AlignEscapedNewlines](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) option to one of the other two values for better readability.

**Comment by nholthaus** [comment]
I'm looking to pull this next. I've never used clang format before so I just have to get it setup first.

**Comment by nholthaus** [comment]
also :heart: `sortIncludes`

**Pull request merged**
