### PR TITLE
Turn the unit aliases into template aliases

### LINKED ISSUE #138: v3.x: abbreviation & name are broken when using integral underlying types
units::unit<meters, int> c;
	EXPECT_STREQ("m", units::abbreviation(c));
	EXPECT_STREQ("meter", units::name(c));
	EXPECT_STREQ("m", c.abbreviation());
	EXPECT_STREQ("meter", c.name());

units.h:109:52: warning: inline function ‘constexpr const char* units::abbreviation(const T&) [with T = units::unit<units::unit_conversion<std::ratio<1>, units::dimension_t<units::dim<units::dimension::length_tag, std::ratio<1, 1> > > >, int>]’ used but never defined

It would also be nice to support querying for name/abbreviation without requiring an object, maybe something like:

	EXPECT_STREQ("ft", units::abbreviation<foot_t>());
	EXPECT_STREQ("foot", units::name<foot_t>());

Another minor thing, in the unit tests the nameAndAbbreviation test case is ifdef'd out by UNIT_LIB_DISABLE_IOSTREAM. That doesn't look quite right.

### LINKED ISSUE #175: Support of data types other than double
I very much like the underlying concepts of `units` and investigate the possibilities to integrate it into our simulation codes, which make heavy use of expression template libraries like `Eigen`, `blaze`, `vexcl` etcetera. That said, I made a first start and changed `UNIT_LIB_DEFAULT_TYPE` from `double` to `float`. The following demo code:

```
#define UNIT_LIB_DEFAULT_TYPE float
#include <units.h>

using namespace units::literals;
using namespace units;
using namespace units::length;
using namespace units::time;
using namespace units::area;
using namespace units::velocity;

int main()
{
    square_meter_t  area = 15_m * 5_m + 10_m * 10_m;        // 175 m^2

    std::cout << area << std::endl;
    
    return 0;
}
```

yields the following compiler error (g++ 8.2):

```
include/units.h:4147:252:   in 'constexpr' expansion of 'units::math::cpow<4, units::unit_t<units::unit<std::ratio<1>, units::base_unit<std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<-1>, std::ratio<0, 1>, std::ratio<0, 1> >, std::ratio<0, 1>, std::ratio<0, 1> > > >(units::constants::N_A)'
include/units.h:2779:17:   in 'constexpr' expansion of 'units::detail::pow((& value)->units::unit_t<units::unit<std::ratio<1>, units::base_unit<std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<0, 1>, std::ratio<-1>, std::ratio<0, 1>, std::ratio<0, 1> >, std::ratio<0, 1>, std::ratio<0, 1> > >::<anonymous>.units::linear_scale<float>::operator()(), 4'
include/units.h:1511:33:   in 'constexpr' expansion of 'units::detail::pow(x, (y + 18446744073709551615))'
include/units.h:1511:33:   in 'constexpr' expansion of 'units::detail::pow(x, (y + 18446744073709551615))'
include/units.h:1511:28: error: '(6.022141e+23f * 6.022141e+23f)' is not a constant expression
    return y == 0 ? 1.0 : x * pow(x, y - 1);
                          ~~^~~~~~~~~~~~~~~
```

The same code compiled by Apple's clang++ yields
```
include/units.h:4147:140: error: constexpr variable 'sigma' must be initialized by a constant expression
  ...inverse<squared<squared<temperature::kelvin>>>>>   sigma((2 * math::cpow<5>(pi) * math::cpow<4>(R)) / (15 * math::cpow<3>(h) * math::cpow<2>(c) * math::cpow<4>(N_A)));    ///< Stefan-Boltz...
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/units.h:1511:28: note: floating point arithmetic produces an infinity
                        return y == 0 ? 1.0 : x * pow(x, y - 1);
                                                ^
include/units.h:1511:30: note: in call to 'pow(6.022141e+23, 2)'
                        return y == 0 ? 1.0 : x * pow(x, y - 1);
                                                  ^
include/units.h:1511:30: note: in call to 'pow(6.022141e+23, 3)'
include/units.h:2779:6: note: in call to 'pow(6.022141e+23, 4)'
                                (detail::pow(value(), power));
                                 ^
include/units.h:4147:235: note: in call to 'cpow(N_A)'
  ...inverse<squared<squared<temperature::kelvin>>>>>   sigma((2 * math::cpow<5>(pi) * math::cpow<4>(R)) / (15 * math::cpow<3>(h) * math::cpow<2>(c) * math::cpow<4>(N_A)));    ///< Stefan-Boltz...
                                                                                                                                                            ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by johelegp**
Resolves #138 
Resolves #175 
and part of #169.

### CODE REVIEW

**Comment by johelegp** [comment]
Adding the changes to `unit` and `abbreviation` done in #150 should fix the remaining errors. I'll do it some time later.

**Comment by johelegp** [comment]
Tell me if I should split 1435f5d into its own PR. Otherwise, this one is ready.

**Comment by nholthaus** [comment]
it's fine this way. Did you already try creating a deduction guide for `<double>` units so users don't have to use templates if they don't want to? If not, I'll work on it some today.

**Comment by johelegp** [comment]
I did try, and failed to conciliate CTAD and defaulting the underlying type to `= double`.

**Comment by nholthaus** [comment]
I'll take another look when we pull strong units. We don't necessarily need a default underlying type anymore, but it would be really nice to deduce the underlying type during construction. It seems like it should be possible to me.

**Pull request merged**
