### PR TITLE
inline namespace constants

### PR DESCRIPTION
**Pull request by nholthaus**
in the spirit of our other namespace inlining, I'm inlining the constants namespace as well

### CODE REVIEW

**Comment by johelegp** [comment]
I hadn't suggested it due to constants like `h`, which clash with their equivalently named `conversion_factor`, due to my desire now expressed in #196, and future constants possibly having the same problem. Not that I suggest using the `conversion_factor`s with the abbreviated name.

**Comment by nholthaus** [comment]
yeah I think we should just change the names of the factors right?

**Comment by johelegp** [comment]
What do you mean? Right now, we have `m`, `meter` and `meters`, which are `conversion_factor`s, and the unit `meter_t`. Following the units' renaming, there would be `m` and `meter`, and `meters`, respectively. There's also the issue of https://github.com/nholthaus/units/issues/159#issuecomment-427608557.

**Comment by nholthaus** [comment]
@johelegp once I clear the PR queue, I'm thinking of ding the unit rename, e,g. removing the `_t`. To do that, I'll first have to change the conversion factor names. I'm thinking unit_name_singular + `_conversion`. What do you think?

Once that's done, the abbreviations will be free again and we can do the `h(1)` defines, as well as define the SI unit of each dimension in `core.h`

**Pull request merged**
